version: '3'

services:

  mongo:
    image: mongo:3.4
    container_name: node-db
    restart: always
    ports:
      - 27017:27017
    networks:
      - main
  mongo-express:
    image: mongo-express:0.49
    restart: always
    ports:
      - 8081:8081
    networks:
      - main
  
  node:
    image: node:11.11
    restart: always
    container_name: node-test
    volumes:
      - /home/panuwat/Desktop/node-tutorial/app:/usr/src/app
    working_dir: /usr/src/app
    networks:
      - main
    command: > 
      sh -c "npm install && node index.js"

networks:
  main:
    external:
      name: main-network