version: "2.4"
services:
  w4l-service-external:
    image: {{ docker_image }}
    container_name: {{ container_name }}
    hostname: w4l-service-external
    volumes:
      - "{{ project_dir }}/service-external:/usr/src/app"
    cpus: 0.15
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.15'
    networks:
      - w4l
      - main
    restart: always
    tty: yes

networks:
  w4l:
    external:
      name: w4l-network
  main:
    external:
      name: main-network
