---
- name: "Include variable from database roles"
  include_vars:
    file: roles/database/vars/main.yml
    name: db
    
- name: "Sending docker-compose to server"
  template:
    src: "{{ item }}"
    dest: "{{ working_dir }}/service-internal/"
  with_items:
    - "docker-compose.yml"

- name: "Sending .env to server"
  template:
    src: "{{ item }}"
    dest: "{{ working_dir }}/service-internal/"
  with_items:
    - ".env"

- name: "Removing existing internal container"
  docker_service:
    project_src: "{{ working_dir }}/service-internal"
    state: absent

- name: "Freshing data"
  file:
    path: "{{ project_dir }}/service-internal"
    state: absent
  become: yes
  become_user: root

- name: "Cloning source from git repository"
  git:
    repo: "{{ service_repo }}"
    version: "{{ service_branch }}"
    dest: "{{ project_dir }}/service-internal"
    accept_hostkey: yes
    force: yes
    key_file: "{{ working_dir }}/common/deploy-key"
  become: yes
  become_user: root

- name: "Copying .env file to container"
  command: cp {{ working_dir }}/service-internal/.env {{ project_dir }}/service-internal/.env
  become: yes
  become_user: root

- name: "Removing node_modules"
  command: rm -rf {{ project_dir }}/service-internal/node_modules
  become: yes
  become_user: root

- name: "Running npm install"
  command: docker run --rm -v {{ project_dir }}/service-internal:/usr/src/app --name {{ container_name }} -w /usr/src/app {{ docker_image }}
           npm install

- name: "Running npm build"
  command: docker run --rm -v {{ project_dir }}/service-internal:/usr/src/app --name {{ container_name }} -w /usr/src/app {{ docker_image }}
           npm run build

- name: "Starting service internal using docker-compose"
  docker_service:
    project_src: "{{ working_dir }}/service-internal"
    state: present

- name: "Installing pm2"
  command: docker exec {{ container_name }} npm install pm2@latest -g

- name: "Update pm2"
  command: docker exec {{ container_name }} pm2 update

- name: "Pm2 running production"
  command: docker exec {{ container_name }} pm2 start --name service_internal npm -- run production --watch

- name: "Pm2 startup"
  command: docker exec {{ container_name }} pm2 startup

- name: "Pm2 save"
  command: docker exec {{ container_name }} pm2 save