version: "3"
services:
  w4l-cms:
    image: php:7.2.12-apache
    container_name: {{ container_name }}
    hostname: w4l-cms
    ports:
      - "3000:80"
    volumes:
      - "{{ project_dir }}/cms/html:/var/www/html"
      - "{{ project_dir }}/cms/images:/var/www/images"
      - "{{ project_dir }}/cms/file:/var/www/file"
    deploy:
      resources:
        limits:
          cpus: '0.15'
    networks:
      - w4l
      - main
    restart: always

networks:
  w4l:
    external:
      name: w4l-network
  main:
    external:
      name: main-network