version: "3.5"
services:
  w4l-cms:
    image: php:7.2.13-apache
    container_name: {{ container_name }}
    hostname: w4l-cms
    ports:
      - "3000:80"
    volumes:
      - "{{ project_dir }}/cms/html:/var/www/html"
      - "/var/www/w4l/images:/var/www/html/images"
      - "/var/www/w4l/file:/var/www/html/file"
    networks:
      - w4l
      - main
    environment:
      API_URL: "{{ api.api_url }}"
    restart: always

networks:
  w4l:
    external:
      name: w4l-network
  main:
    external:
      name: main-network
