version: "2.4"
services:
  w4l-api:
    image: {{ docker_image }}
    container_name: {{ container_name }}
    hostname: w4l-api
    command: "npm start"
    ports:
      - "5000:5000"
    volumes:
      - "{{ project_dir }}/api:/usr/src/app"
    cpus: 0.15
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.15'
    networks:
      - w4l
      - main
    restart: always
    tty: yes
    

networks:
  w4l:
    external:
      name: w4l-network
  main:
    external:
      name: main-network