version: "3"
services:
  node-api:
    image: node:11.11
    container_name: {{ container_name }}
    hostname: node-api
    ports:
      - "9000:3000"
    volumes:
      - "{{ project_dir }}/api:/usr/src/app"
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
      - TZ=Asia/Bangkok
    networks:
      - nodetuterial
      - main
    restart: always
    tty: yes
    

networks:
  nodetuterial:
    external:
      name: node-network
  main:
    external:
      name: main-network