version: "3.5"
services:
  w4l-api:
    image: {{ docker_image }}
    container_name: {{ container_name }}
    hostname: w4l-api
    ports:
      - "5000:5000"
    volumes:
      - "{{ project_dir }}/api:/usr/src/app"
    deploy:
      resources:
        limits:
          cpus: '0.15'
    networks:
      - w4l
      - main
    restart: always
    tty: yes

networks:
  w4l:
    external:
      name: w4l-network
  main:
    external:
      name: main-network