---
- name: "Sending docker-compose and dockerfile to server"
  template:
    src: "{{ item }}"
    dest: "{{ working_dir }}/api/"
  with_items:
    - "docker-compose.yml"
    
- name: "Removing existing API container"
  docker_service:
    project_src: "{{ working_dir }}/api"
    state: absent

- name: "Freshing data"
  file:
    path: "{{ project_dir }}/api"
    state: absent
  become: yes
  become_user: root

- name: "Cloning source from git repository"
  git:
    repo: "{{ api_repo }}"
    version: "{{ api_branch }}"
    dest: "{{ project_dir }}/api"
    # accept_hostkey: yes
    # force: yes
    # key_file: "{{ working_dir }}/common/deploy-key"
  become: yes
  become_user: root

- name: "Removing node_modules"
  command: rm -rf {{ project_dir }}/api/node_modules
  become: yes
  become_user: root
  
- name: "Starting service api using docker-compose"
  docker_service:
    project_src: "{{ working_dir }}/api"
    state: present

- name: "Running npm install"
  command: docker exec -w /usr/src/app {{ container_name }}
           npm install