---
- name: "Sending docker-compose to server"
  template:
    src: "{{ item }}"
    dest: "{{ working_dir }}/db/"
  with_items:
    - "docker-compose.yml"

- name: "Removing existing DB container"
  docker_service:
    project_src: "{{ working_dir }}/db"
    state: absent

- name: "Freshing data"
  file:
    path: "{{ project_dir }}/db"
    state: absent
  become: yes
  become_user: root

- name: "Starting mariadb using docker-compose"
  docker_service:
    project_src: "{{ working_dir }}/db"
    state: present

- name: "Testing mariadb connection"
  command: docker exec {{ container_name }} mysqlshow -u {{ user }} -p{{ password }}
  register: result
  until: result.rc == 0
  retries: 10
  delay: 3

- name: "Downloading sql file to server"
  command: curl https://storage.lepusastro.com/s/VPXksJZT2p2jqz8/download --output {{ working_dir }}/db/w4l.sql

- name: "Copying sql file to container"
  command: docker cp {{ working_dir }}/db/w4l.sql
          {{ container_name }}:/
