---
- name: "Sending docker-compose to server"
  template:
    src: "{{ item }}"
    dest: "{{ working_dir }}/db/"
  with_items:
    - "docker-compose.yml"

- name: "Removing existing DB container"
  docker_service:
    project_src: "{{ working_dir }}/db"
    state: absent

- name: "Freshing data"
  file:
    path: "{{ project_dir }}/db"
    state: absent
  become: yes
  become_user: root

- name: "Cloning source from git repository"
  git:
    repo: "{{ db_repo }}"
    version: "{{ db_branch }}"
    dest: "{{ project_dir }}/db"
    # accept_hostkey: yes
    # force: yes
    # key_file: "{{ working_dir }}/common/deploy-key"
  become: yes
  become_user: root

- name: "Starting mongo-database using docker-compose"
  docker_service:
    project_src: "{{ working_dir }}/db"
    state: present