# Container configuration
container_name: "w4l.service.internal"
docker_image: "node:11.0.0"

# Environment variables

PORT : "3000"
LIMIT : "10"
ALLOW_TOKEN : "5464372f-b619-545e-ac7d-7d516517d471"
SERVICE_FILES_IP : "http://w4l.service.files:4000"

DL_NEWS_SOURCE_DOMAIN : "http://202.129.59.68/"
DL_NEWS_SOURCE_PATH_IMAGE : "uploads/images/news/"
DL_NEWS_SOURCE_PATH : "uploads/file/news/"
DL_NEWS_SAVE_PATH_IMAGE : "images/news/"
DL_NEWS_SAVE_PATH : "files/news/"

DL_WATER_SITUATION_DAILIES_SOURCE_DOMAIN : "http://202.129.59.68/"
DL_WATER_SITUATION_DAILIES_SOURCE_PATH : "uploads/file/statuswater/"
DL_WATER_SITUATION_DAILIES_SAVE_PATH : "files/water_situation_dailies/"

DL_CCTV_WATER_LEVEL_SOURCE_DOMAIN : "http://202.129.59.68/"
DL_CCTV_WATER_LEVEL_SOURCE_PATH : "uploads/file/statuswater/"
DL_CCTV_WATER_LEVEL_SAVE_PATH : "files/cctv_water_level/"

DL_KNOWLEDGE_SOURCE_DOMAIN : "http://system.dwr.go.th/"
DL_KNOWLEDGE_SOURCE_PATH : "knowladge/phocadownload/"
DL_KNOWLEDGE_SAVE_PATH : "files/knowledge/"

DL_WARNING_FLOOD_LANDSLIDES_REPORT_SOURCE_DOMAIN : "http://202.129.59.68/"
DL_WARNING_FLOOD_LANDSLIDES_REPORT_SOURCE_PATH : "uploads/file/statuswater/"
DL_WARNING_FLOOD_LANDSLIDES_REPORT_SAVE_PATH : "files/warning_flood_landslides_report/"
