version: '3'
services:
  web-apiwater4life:
    image: php:7.1-apache
    container_name: {{ php_container_name }}
    hostname: php-api-water4life
    restart: always
    networks:
      - main
      - apiwater4life
    volumes:
      - {{ project_dir }}/code/website:/var/www/html
      - {{ project_dir }}/apache:/etc/apache2/sites-availables
    environment:
      - VIRTUAL_HOST=demo.api.water4life.piesoft.net
      - LETSENCRYPT_HOST=demo.api.water4life.piesoft.net
      - LETSENCRYPT_EMAIL=water4life@piesoft.net

  db-apiwater4life:
    image: mariadb
    container_name: {{ db_container_name }}
    hostname: mariadb-apiwater4life
    restart: always
    networks:
      - apiwater4life
    volumes:
      - {{ project_dir }}/db/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD={{ db_root_password }}
      - MYSQL_DATABASE={{ db_name }}
      - MYSQL_USER={{ db_user }}
      - MYSQL_PASSWORD={{ db_password }}
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
    ports:
        - "33306:3306"

networks:
  apiwater4life:
    external:
      name: apiwater4life-network
  main:
    external:
      name: main-network
