---
- name: "Sent file to target server"
  copy:
    dest: "{{ temporary_dir }}/key/"
    src: "{{ item }}"
    mode: 0600
  with_items:
    - "deploy-key"

- name: "Sent file to target server with changes variables"
  template:
    src: "{{ item }}"
    dest: "{{ temporary_dir }}/composefile/"
  with_items:
    - "docker-compose.yml"

- name: "Clone deployment scripts"
  git:
    repo: git@projects.piesoft.net:DWR/Water4Life/API.git
    version: "{{ branch }}"
    dest: "{{ temporary_dir }}/code"
    accept_hostkey: yes
    key_file: "{{ temporary_dir }}/key/deploy-key"

- name: "Copy source code to mount directory"
  shell: rsync -Pav --delete --recursive {{ temporary_dir }}/code/ {{ project_dir }}/code/website/
  become: true
  become_user: root

- name: "Change permission in source code directory"
  file:
    path: "{{ project_dir }}/code/website"
    state: directory
    owner: www-data
    group: www-data
    recurse: yes
  become: true
  become_user: root

- name: "Run composer install"
  shell: docker run --rm -v {{ project_dir }}/code/website:/app composer install

- name: "Run npm install"
  shell: docker run --rm -v {{ project_dir }}/code/website:/app -w /app node:9 npm install

- name: "Create env file"
  template: 
    src: ".env"
    dest: "{{ project_dir }}/code/website/"
  become: true
  become_user: root

- name: "Sent apache configuration file to server"
  copy:
    dest: "{{ temporary_dir }}"
    src: apache

- name: "Move apache configuration file to mount dir"
  shell: rsync -Pav --delete --recursive {{ temporary_dir }}/apache {{ project_dir }}/
  become: true
  become_user: root

#- name: "Clean DB data mount dir"
  #file:
    #path: "{{ project_dir }}/db/data"
    #state: absent
  #become: true
  #become_user: root

- name: "Start container with docker-compose"
  shell: docker-compose -f {{ temporary_dir }}/composefile/docker-compose.yml up -d

- name: "Install lib mysql"
  shell: docker exec {{ php_container_name }} bash -c 'docker-php-ext-install pdo_mysql'

- name: "Waiting for db up 10s ..."
  pause:
    seconds: 10

- name: "Migrate DB"
  shell: docker exec {{ php_container_name }} bash -c 'cd /var/www/html && php artisan migrate'

- name: "Migrate DB rollback"
  shell: docker exec {{ php_container_name }} bash -c 'cd /var/www/html && php artisan migrate:rollback'

- name: "Refresh DB"
  shell: docker exec {{ php_container_name }} bash -c 'cd /var/www/html && php artisan migrate:refresh --seed'

- name: "Enable Token Generator"
  shell: docker exec {{ php_container_name }} bash -c 'cd /var/www/html && php artisan passport:install'

- name: "Enabled mod_rewrite on apache2"
  shell: docker exec {{ php_container_name }} bash -c 'a2enmod rewrite'

- name: "Restart service apache2"
  shell: docker restart {{ php_container_name }}
