---
- name: "Cleaning working direcotry"
  file:
    path: "{{ working_dir }}"
    state: absent
  become: true
  become_user: root

- name: "Creating working directory"
  file:
    path: "{{ working_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: root
  become: true
  become_user: root

- name: "Installing python pip"
  apt:
    name: python-pip
  become: yes
  become_user: root

- name: "Installing docker-py via pip"
  pip:
    name: "{{ item }}"
  with_items:
    - "docker-compose"
  become: yes
  become_user: root

- name: "Create common working dir"
  file:
    path: "{{ working_dir }}/common"
    state: directory

- name: "Sending Deploy key to target server"
  copy:
    src: deploy-key
    dest: "{{ working_dir }}/common/"
    mode: 0600

- name: "Creating docker networks"
  docker_network:
    name: "{{ item }}"
    state: "present"
  with_items:
    - "main-network"
    - "w4l-network"