---
- name: "Create temporary directory"
  file:
    path: "{{ temporary_dir }}/{{ item }}"
    state: directory
  with_items:
    - "key"
    - "code"
    - "composefile"
    - "apache"

- name: "Create mount directory"
  file:
    path: "{{ project_dir }}/{{ item }}"
    state: directory
  with_items:
    - "code/website"
    - "apache"
    - "db"
  become: true
  become_user: root

- name: "Create docker networks"
  shell: docker network create {{ item }}
  with_items:
    - "main-network"
    - "apiwater4life-network"
  ignore_errors: yes

- name: "Remove running container"
  shell: docker rm -f {{ item }}
  with_items:
    - "{{ php_container_name }}"
    - "{{ db_container_name }}"
  ignore_errors: yes
