---
- name: "Removing working_dir"
  command: rm -rf {{ working_dir }}/api/node_modules
  become: yes
  become_user: root

- name: "Cleaning working direcotry"
  file:
    path: "{{ working_dir }}"
    state: absent
  become: true
  become_user: root

- name: "Creating working directory"
  file:
    path: "{{ working_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: root
  become: true
  become_user: root

- name: "Installing python pip"
  apt:
    name: python-pip
  become: yes
  become_user: root

- name: "Installing docker-py via pip"
  pip:
    name: "{{ item }}"
  with_items:
    - "docker-compose"
  become: yes
  become_user: root

- name: "Creating docker networks"
  docker_network:
    name: "{{ item }}"
    state: "present"
  with_items:
    - "main-network"
    - "node-network"
